-- Global recovery-email destination for the hidden admin password-reset OTP flow.
ALTER TABLE `company_settings` ADD COLUMN `recoveryEmail` VARCHAR(191) NULL;

-- New audit event types for the recovery flow.
ALTER TABLE `audit_logs` MODIFY COLUMN `eventType` ENUM('LOGIN_SUCCESS','LOGIN_FAILURE','LOGOUT','TOKEN_REFRESH','TOKEN_REUSE_DETECTED','PASSWORD_RESET_REQUESTED','PASSWORD_RESET_COMPLETED','EMPLOYEE_CREATED','EMPLOYEE_UPDATED','EMPLOYEE_DEACTIVATED','EMPLOYEE_REACTIVATED','ATTENDANCE_PUNCH_IN','ATTENDANCE_PUNCH_OUT','ATTENDANCE_CREATED','ATTENDANCE_UPDATED','ATTENDANCE_DELETED','LEAVE_REQUESTED','LEAVE_APPROVED','LEAVE_REJECTED','LEAVE_CANCELLED','LEAVE_BALANCE_ADJUSTED','LEAVE_TYPE_CREATED','LEAVE_TYPE_UPDATED','SALARY_CREATED','SALARY_UPDATED','SALARY_STATUS_CHANGED','SALARY_PAID','DEPARTMENT_CREATED','DEPARTMENT_UPDATED','DESIGNATION_CREATED','DESIGNATION_UPDATED','SHIFT_CREATED','SHIFT_UPDATED','EMPLOYEE_SHIFT_ASSIGNED','HOLIDAY_CREATED','HOLIDAY_UPDATED','HOLIDAY_DELETED','SETTINGS_UPDATED','USER_ROLE_CHANGED','REPORT_EXPORTED','ANNOUNCEMENT_CREATED','ANNOUNCEMENT_UPDATED','ANNOUNCEMENT_DELETED','SALARY_ADVANCE_RECORDED','SALARY_ADVANCE_DELETED','LEGACY_DATA_IMPORTED') NOT NULL;

-- OTP + one-time reset-token records for the recovery flow.
CREATE TABLE `password_reset_otps` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `codeHash` VARCHAR(191) NOT NULL,
    `codeExpiresAt` DATETIME(3) NOT NULL,
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `consumedAt` DATETIME(3) NULL,
    `resetTokenHash` VARCHAR(191) NULL,
    `resetTokenExpiresAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `password_reset_otps_userId_idx`(`userId`),
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `password_reset_otps` ADD CONSTRAINT `password_reset_otps_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
